import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import { ThemeContextProvider } from "@/context/ThemeContext"; 
import NavBar from "@/components/NavBar";
import ClientOnlySnackbarProvider from "@/components/ClientOnlySnackbarProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeContextProvider> {/* заменува ThemeRegistry */}
          <ClientOnlySnackbarProvider>
            <CartProvider>
              <NavBar />
              {children}
            </CartProvider>
          </ClientOnlySnackbarProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
